### PR TITLE
Rename folders to address #25

### PR DESCRIPTION
**Pull request by arush-sal**

### CODE REVIEW

**Comment by Govinda-Fichtner** [comment]
@arush-sal Did you change the the markdown links that were referencing files in the repository, too?

**Comment by arush-sal** [comment]
Sorry, I missed doing so, It has been fixed now.

**Comment by Govinda-Fichtner** [comment]
@arush-sal I think I might have not described exactly what I meant:
Look at this file: https://github.com/DevOps-Academy-Org/dca-prep-guide/blob/master/domain2/Demonstrate_tagging_an_image.md

The link there is not correct any more. There a couple of internal links that do not work after your changes. They need to be fixed.

I did not mean to add the links for the chapters.

**Comment by arush-sal** [comment]
@Govinda-Fichtner Thank you for the explanation. There were only two such links found and I have fixed both, one in Domain 2 and another in Domain 6. Also, I have squashed all of my commits. Let me know if anything else is required. Thank you for your patience :)

**Pull request merged**
